server:
  port: 8081

spring:
  application:
    name: "Catalog Service"
  datasource:
    url: jdbc:mysql://localhost:3306/catalogdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: false
    change-log: classpath:/db.changelog/changelog-master.xml


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api/catalog/swagger-ui.html